---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Accueil
- type: directory
  path: data/home
  label: Services
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - services
- type: heading
  label: Pages
- type: document
  path: data/pages/coaching.md
  label: Coaching
- type: directory
  path: data/soins
  label: Soins
  create: documents
  match: "**/*"
  templates:
  - general-page
- type: document
  path: data/pages/cure.md
  label: Cure
- type: directory
  path: data/bio
  label: Bio
  create: documents
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: gridsome develop -p 8080 -h 0.0.0.0
