---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Général
- type: document
  path: data/site.yaml
  label: Options du site
- type: heading
  label: Français
- type: directory
  path: data/carousel
  label: Carousel
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data/home
  label: Accueil
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - services
  - lead
  - home-formations
- type: document
  path: data/pages/coaching.md
  label: Coaching
- type: directory
  path: data/linkedIn
  label: LinkedIn
  create: documents
  match: "**/*"
  templates:
  - linkedin
- type: directory
  path: data/soins
  label: Soins
  create: documents
  match: "**/*"
  templates:
  - general-page
- type: document
  path: data/pages/cure.md
  label: Cures
- type: directory
  path: data/formations
  label: Formations
  create: documents
  match: "**/*"
  templates:
  - formations
- type: directory
  path: data/boutique
  label: Boutique
  create: all
  match: "**/*"
  templates:
  - products
- type: directory
  path: data/articles
  label: Blogue
  create: all
  match: "**/*"
  templates:
  - blogue
- type: directory
  path: data/bio
  label: Bio
  create: all
  match: "**/*"
- type: heading
  label: Anglais
- type: directory
  path: data_en/carousel
  label: Carousel
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data_en/home
  label: Home
  create: all
  match: "**/*"
  templates:
  - services
  - lead
  - home-formations
- type: document
  path: data_en/pages/coaching.md
  label: Coaching
- type: directory
  path: data_en/services
  label: Services
  create: all
  match: "**/*"
  templates:
  - general-page
- type: directory
  path: data_en/linkedIn
  label: LinkedIn
  create: documents
  match: "**/*"
  templates:
  - linkedin
- type: document
  path: data_en/pages/detox.md
  label: Detox
- type: directory
  path: data_en/training
  label: Training
  create: all
  match: "**/*"
  templates:
  - formations
- type: directory
  path: data_en/shop
  label: Shop
  create: all
  match: "**/*"
  templates:
  - products
- type: directory
  path: data_en/bio
  label: Bio
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gridsome develop -p 8080 -h 0.0.0.0
