---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Accueil
- type: directory
  path: data/home
  label: Services
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - services
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
