---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Titre
- name: categorie
  type: tag_list
  default: []
  label: Catégorie
- type: text
  name: url
  label: Lien externe
  description: Lien vers la boutique du produit
- type: file
  name: thumbnail
  label: Image
