---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Titre
- name: order
  type: number
  label: Ordre
  description: Ordre d'affichage dans la page
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: categorie
  type: tag_list
  default: []
  label: Catégorie
- type: text
  name: url
  label: Lien externe
  description: Lien vers la boutique du produit
- type: file
  name: thumbnail
  label: Vignette
  description: Vignette pour la page boutique
- name: featured_image
  type: file
  config:
    maxSize: 
  label: Image
  description: Image de la page du produit
