---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Titre
- name: categorie
  type: tag_list
  default: []
  label: Catégorie
- type: text
  name: url
  label: Lien externe
  description: Lien vers la boutique du produit
- type: file
  name: thumbnail
  label: Vignette
  description: Vignette pour la page boutique
- name: featured_image
  type: file
  config:
    maxSize: 250
  label: Image
  description: Image de la page du produit
