---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Titre
- type: text
  name: url
  label: Lien externe
  description: Lien vers la boutique du produit
- type: file
  name: thumbnail
  label: Image
