---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: Titre
  config:
    required: true
- type: file
  name: thumbnail
  label: thumbnail
- type: number
  name: Position
  label: Position
  description: Ordre d'affichage du service
