---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: Titre
  config:
    required: true
- type: file
  name: thumbnail
  label: Image
- type: number
  name: Position
  label: Position
  description: Ordre d'affichage du service
pages:
- data/home/cure.md
- data/home/soins.md
- data/home/coaching.md
- data/home/call-to-action.md
